JobHunt/Areas/Admin/Controllers/NewManagementController.cs
using ClosedXML.Excel;
using JobHunt.BU.DTO;
using JobHunt.BU.Manage;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace JobHunt.Areas.Admin.Controllers
{
    [Authorize(Roles = "Quản trị, Quản lý tin tức")]
    public class NewManagementController : Controller
    {
        NewManage newmanage = new NewManage();
        // GET: Admin/NewManagement
        public ActionResult Index()
        {
            var model = newmanage.GetAllNews();
            return View(model);
        }

        public ActionResult CreateNew()
        {
            ViewBag.ListCategories = new SelectList(new NewManage().GetListCategories(), "CategoryId", "CName");
            return View();
        }


        [ValidateInput(false)]
        public JsonResult CUNew(NewDTO ndto, int? typePost)
        {
            var resultMessage = "";
            var resultStatus = "error";
            var resultCode = 0;

            //typePost = 1: create new
            if (typePost == 1)
            {
                ndto.NPostDate = DateTime.Now;
                ndto.N_WebmasterInfoId = 2;
                var insert = newmanage.Insert(ndto);
                if (insert != null)
                {
                    resultCode = 1;
                    resultMessage = "Tạo thành công";
                    resultStatus = "success";
                    string path = Server.MapPath("/Assets/template/SendMailToRegisterTinRao.html");
                    ParameterizedThreadStart job = new ParameterizedThreadStart(SendEmail);
                    Thread thread = new Thread(job);
                    thread.Start(new EmailClient() { TieuDe = insert.NTitle, Path = path, newdto = insert });
                }
                else
                {
                    resultMessage = "Đăng tin thất bại";
                }
            }
            //typePost = 2: update new
            else
            {
                resultCode = newmanage.Update(ndto);
                if (resultCode == 1)
                {
                    resultMessage = "Sửa thành công";
                    resultStatus = "success";
                }
                else
                {
                    resultMessage = "Sửa tin thất bại";
                }
            }
            return Json(new { code = resultCode, message = resultMessage, status = resultStatus }, JsonRequestBehavior.AllowGet);
        }

        class EmailClient
        {
            public string TieuDe { get; set; }
            public string Hinhthuc { get; set; }
            public string Path { get; set; }
            public int? IdPro { get; set; }
            public NewDTO newdto { get; set; }
        }
        // string tieuDe, int codeInsert, string hinhthuc
        static void SendEmail(object obj)
        {
            var job = obj as EmailClient;
            var getListRegisters = new SignUpNewsletterManage().GetListSignUpByType(1, job.IdPro);
            foreach (var j in getListRegisters)
            {
                SendMailToRegister(job.Path, j.Name, "tin tức", "http://103.237.147.20:333/tin-tuc/" + BU.Common.GenerateUrl.GenerateSlug(job.newdto.NTitle, job.newdto.NewsId), j.Email);
            }
        }
        public static int SendMailToRegister(string path, string name, string tenht, string link, string mail)
        {
            int resultCode = 0;
            try
            {
                string content = System.IO.File.ReadAllText(path);
                content = content.Replace("{{name}}", name);
                content = content.Replace("{{tenhinhthuc}}", tenht);
                content = content.Replace("{{link}}", link);
                var senderEmail = new MailAddress("bboyhn9x@gmail.com", "3FGROUP");
                var receiverEmail = new MailAddress(mail);
                var password = "22081995A";
                var sub = "Thông báo từ tìm việc làm VNUA";
                var body = content;
                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(senderEmail.Address, password)
                };
                using (var mess = new MailMessage(senderEmail, receiverEmail)
                {
                    Subject = sub,
                    Body = body
                })
                {
                    smtp.Send(mess);
                }
                resultCode = 1;
            }
            catch (Exception)
            {
                resultCode = 2;
            }
            return resultCode;
        }


        //Delete new
        public JsonResult DeleteNew(int? idNew)
        {
            var resultCode = 0;
            var resultMessage = "";
            var resultStatus = "error";
            if (idNew == null || idNew == 0)
            {
                resultMessage = "Mã tin tức không được để trống";
            }
            else
            {
                resultCode = newmanage.Delete((int)idNew);
                if (resultCode == 1)
                {
                    resultMessage = "Xóa thành công";
                    resultStatus = "success";
                }
                else
                {
                    resultMessage = "Đã xảy ra lỗi khi xóa";
                }
            }
            return Json(new { message = resultMessage, status = resultStatus, code = resultCode }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult DetailNew(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = newmanage.GetBlogById((int)id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.ListCategories = new SelectList(newmanage.GetListCategories(), "CategoryId", "CName");
            return View(model);
        }
        // Upload Image
        [HttpPost]
        public string UploadFileImageSumernote(HttpPostedFileBase file)
        {
            var pic = System.Web.HttpContext.Current.Request.Files["file"];
            // Validate
            // Xử lý upload lưu vào sv
            file.SaveAs(Server.MapPath("~/Assets/admin/upload/summernoteimages/" + file.FileName));
            // Trả về link ảnh
            return "/Assets/admin/upload/summernoteimages/" + file.FileName;
        }

        // Upload Image
        [HttpPost]
        public string UploadFileImageNew(HttpPostedFileBase file)
        {
            var pic = System.Web.HttpContext.Current.Request.Files["file"];
            // Validate
            // Xử lý upload lưu vào sv
            file.SaveAs(Server.MapPath("~/Assets/admin/upload/newimages/" + file.FileName));
            // Trả về link ảnh
            return "/Assets/admin/upload/newimages/" + file.FileName;
        }

        //export to excel
        [HttpPost]
        public FileResult ExportToExcel(string keyWord, int? Status)
        {
            //Sheet Tổng Quan
            DataTable dtIndex = new DataTable("DanhSachTinTuc");

            dtIndex.Columns.AddRange(new DataColumn[6] {new DataColumn("STT"),
                                                    new DataColumn("Ảnh đại diện"),
                                                    new DataColumn("Tiêu đề"),
                                                    new DataColumn("Nội dung ngắn gọn"),
                                                    new DataColumn("Trạng thái"),
                                                    new DataColumn("Thể loại"),
                                                   });

            var model = newmanage.GetListNewsBySearch(keyWord, Status);

            var stt = 0;

            foreach (var newdto in model)
            {
                stt++;
                Image image1 = Image.FromFile(Server.MapPath("~" +newdto.NAvatar));

                // Draw the image.
                dtIndex.Rows.Add(stt, newdto.NAvatar, newdto.NTitle, newdto.NQuote, newdto.NameStatus, newdto.NameType);
            }


            using (XLWorkbook wb = new XLWorkbook())
            {
                var ws = wb.Worksheets.Add(dtIndex);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "DanhSachTinTuc.xlsx");
                }
            }
        }
    }
}

JobHunt/Areas/Admin/Controllers/RecruitManagementController.cs
using ClosedXML.Excel;
using JobHunt.BU.DTO;
using JobHunt.BU.Manage;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace JobHunt.Areas.Admin.Controllers
{
    [Authorize(Roles = "Quản trị, Quản lý người tuyển dụng, Quản lý người tìm việc")]
    public class RecruitManagementController : Controller
    {
        // GET: Admin/RecruitManagement
        ProfessionManage ProfessionManage = new ProfessionManage();
        CityManage cityManage = new CityManage();
        RecruitJobManage recruitjobManage = new RecruitJobManage();
        RecruitManage recruitManage = new RecruitManage();
        CandidateManage candidateManage = new CandidateManage();
        public ActionResult Index()
        {
            var model = recruitManage.GetListRecruits();
            return View(model);
        }

        //
        public ActionResult CreateRecruit()
        {
            //Lấy ra danh sách tất cả danh mục công việc
            ViewBag.ListProfesstions = new SelectList(ProfessionManage.GetAllProfessions(), "ProfessionId", "PFName");

            //Lấy danh sách tỉnh
            ViewBag.ListCities = new SelectList(cityManage.GetAllCities(), "CityId", "CName");

            //Lấy danh sách trình độ
            ViewBag.ListLevels = new SelectList(new LevelManage().GetAllLevels(), "LevelInfoId", "LIName");

            //Lấy danh sách kinh nghiệm
            ViewBag.ListExperiences = new SelectList(new ExperienceManage().GetAllExperiences(), "ExperienceId", "EShow");

            //Lấy danh sách kinh Lương
            ViewBag.ListSalaries = new SelectList(new SalaryMange().GetAllSalaries(), "SalaryId", "SShow");

            //Lấy danh sách hình thức làm việc
            ViewBag.ListWorkTypes = new SelectList(new WorkTypeManage().GetAllWorkTypes(), "WorkTypeId", "WTName");

            //Lấy ra danh sách size của công ty
            ViewBag.ListCompanySizes = new SelectList(new CompanySizeManage().GetAllCompanySizes(), "CompanySizeId", "CSShow");

            return View();
        }


        //
        public ActionResult DetailRecruit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = recruitManage.GetRecruitInfoById((int)id);
            if (model == null)
            {
                return HttpNotFound();
            }

            //Lấy ra danh sách tất cả danh mục công việc
            ViewBag.ListProfesstions = new SelectList(ProfessionManage.GetAllProfessions(), "ProfessionId", "PFName");

            //Lấy danh sách tỉnh
            ViewBag.ListCities = new SelectList(cityManage.GetAllCities(), "CityId", "CName");

            //Lấy danh sách trình độ
            ViewBag.ListLevels = new SelectList(new LevelManage().GetAllLevels(), "LevelInfoId", "LIName");

            //Lấy danh sách kinh nghiệm
            ViewBag.ListExperiences = new SelectList(new ExperienceManage().GetAllExperiences(), "ExperienceId", "EShow");

            //Lấy danh sách kinh Lương
            ViewBag.ListSalaries = new SelectList(new SalaryMange().GetAllSalaries(), "SalaryId", "SShow");

            //Lấy danh sách hình thức làm việc
            ViewBag.ListWorkTypes = new SelectList(new WorkTypeManage().GetAllWorkTypes(), "WorkTypeId", "WTName");

            //Lấy ra danh sách size của công ty
            ViewBag.ListCompanySizes = new SelectList(new CompanySizeManage().GetAllCompanySizes(), "CompanySizeId", "CSShow");

            return View(model);
        }


        //
        public JsonResult UpdateRecruit(RecruitDTO rcdto, int? type)
        {
            var resultCode = 0;
            var resultMessage = "";
            var resultStatus = "error";
            if (rcdto.RecruitId == 0)
            {
                resultMessage = "Mã NTD không được để trống";
            }
            else
            {
                if(type == 1)
                {
                    resultCode = recruitManage.Insert(rcdto);
                    if (resultCode == 1)
                    {
                        resultMessage = "Thêm thành công";
                        resultStatus = "success";
                    }
                    else
                    {
                        resultMessage = "Thêm không thành công";
                    }
                }
                else
                {
                    resultCode = recruitManage.UpdateRecruit(rcdto);
                    if (resultCode == 1)
                    {
                        resultMessage = "Cập nhật thành công";
                        resultStatus = "success";
                    }
                    else
                    {
                        resultMessage = "Sửa không thành công";
                    }
                }
            }
            return Json(new { message = resultMessage, status = resultStatus, code = resultCode }, JsonRequestBehavior.AllowGet);
        }

        //
        public JsonResult DeleteRecruit(int? idRecruit)
        {
            var resultCode = 0;
            var resultMessage = "";
            var resultStatus = "error";
            if (idRecruit == null || idRecruit == 0)
            {
                resultMessage = "Mã NTD không được để trống";
            }
            else
            {
                resultCode = recruitManage.Delete((int)idRecruit);
                if (resultCode == 1)
                {
                    resultMessage = "Xóa thành công";
                    resultStatus = "success";
                }
                else
                {
                    resultMessage = "Đã xảy ra lỗi khi xóa";
                }
            }
            return Json(new { message = resultMessage, status = resultStatus, code = resultCode }, JsonRequestBehavior.AllowGet);
        }

        //export to excel
        [HttpPost]
        public FileResult ExportToExcel(string keyWord, int? Status)
        {
            //Sheet Tổng Quan
            DataTable dtIndex = new DataTable("DanhSachNTD");

            dtIndex.Columns.AddRange(new DataColumn[7] {new DataColumn("STT"),
                                                    new DataColumn("Tên đăng nhập"),
                                                    new DataColumn("Tên đầy đủ"),
                                                    new DataColumn("Ngày đăng ký"),
                                                    new DataColumn("Vị trí làm việc"),
                                                    new DataColumn("Tỉnh/Thành phố"),
                                                    new DataColumn("Trạng thái")
                                                   });

            var model = recruitManage.GetListRecruitsBySearch(keyWord, Status);

            var stt = 0;
            foreach (var rc in model)
            {
                stt++;
                dtIndex.Rows.Add(stt, rc.AspNetUserDTO.UserName, rc.RIFullName, rc.RIRegisterDate.Value.ToShortDateString(), rc.ProfessionDTO.PFName, rc.CityDTO.CName, rc.StatusString);
            }


            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dtIndex);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "DanhSachNTD.xlsx");
                }
            }
        }
    }
}

JobHunt/Areas/Admin/Views/DashBoard/Index.cshtml
@model List<JobHunt.BU.DTO.AdvertisementDTO>
    @using JobHunt.BU.DTO
@{
    /**/

    ViewBag.Title = "Trang quản trị || VNUA";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var stt = 0;

    //List jobs
    var ListJobs = (List<RecruitJobDTO>)ViewBag.ListTopFindJob;
}
    <script>
    $(document).ready(function () {
        localStorage.setItem("totalDashboard","@ViewBag.NumberDashboard");
    });
    </script>

<section class="listSupplier main__content">
    <div class="listcm__top main__banner dashboard__banner">
        <div class="row">
            <div class="col-12">
                <div class="main__title">
                    <h1 class="main__title--content dashboard-title">Dashboard</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="listcm__content main__list dashboard__list">
        <div class="list__top main__list--top">
            <div class="row">
                <div class="col-lg-3 col-6">
                    <div class="dashboard--item">
                        <div class="dashboard--item__content blue">
                            <div class="dashboard--item__top">
                                <h2 class="dashboard--item__number">
                                    <input type="text" name="name" id="TotalAccumulated" class="readonly" value="@ViewBag.NumberAccountCandidate" />
                                </h2>
                                <p class="dashboard--item__name">Tài khoản người tìm việc</p>
                                <div class="icon"><i class="fa fa-signal"></i></div>
                            </div>
                            <div class="dashboard--item__btn text-center">
                                <a href="@Url.Action("","candidatemanagement")" class="text-center">
                                    Xem chi tiết
                                    <span><i class="fa fa-arrow-circle-right"></i></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-6">
                    <div class="dashboard--item">
                        <div class="dashboard--item__content green">
                            <div class="dashboard--item__top">
                                <h2 class="dashboard--item__number">
                                    <input type="text" name="name" id="TotalAccumulatedMember" class="readonly" value="@ViewBag.NumberAccountRecruit" />
                                </h2>
                                <p class="dashboard--item__name">Tài khoản nhà tuyển dụng</p>
                                <div class="icon"><i class="fa fa-user"></i></div>
                            </div>
                            <div class="dashboard--item__btn text-center">
                                <a href="@Url.Action("","RecruitManagement")" class="text-center">
                                    Xem chi tiết
                                    <span><i class="fa fa-arrow-circle-right"></i></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-6">
                    <div class="dashboard--item">
                        <div class="dashboard--item__content orange">
                            <div class="dashboard--item__top">
                                <h2 class="dashboard--item__number">
                                    <input type="text" name="name" id="TotalHistoryConstruction" class="readonly" value="@ViewBag.NumberJob" />
                                </h2>
                                <p class="dashboard--item__name">Công việc</p>
                                <div class="icon"><i class="fa fa-building"></i></div>
                            </div>
                            <div class="dashboard--item__btn text-center">
                                <a href="@Url.Action("","recruitjobmanagement")" style="cursor:pointer;" class="text-center view-detail-hcd">
                                    Xem chi tiết
                                    <span><i class="fa fa-arrow-circle-right"></i></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-6">
                    <div class="dashboard--item">
                        <div class="dashboard--item__content red">
                            <div class="dashboard--item__top">
                                <h2 class="dashboard--item__number">
                                    <input type="text" name="name" id="TotalAccumulatedByMonth" class="readonly" value="@ViewBag.NumberNew" />
                                </h2>
                                <p class="dashboard--item__name">Bài viết, tin tức</p>
                                <div class="icon"><i class="fa fa-calendar"></i></div>
                            </div>
                            <div class="dashboard--item__btn text-center">
                                <a href="@Url.Action("","NewManagement")" class="text-center">
                                    Xem chi tiết
                                    <span><i class="fa fa-arrow-circle-right"></i></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="dashboard__content">
            <div class="dashboard__content--banner">
                <div class="row">
                    <div class="col-8">
                        <div class="dashboard__content--title">
                            <h2 class="dashboard-title">Danh sách quảng cáo đến hạn</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="dashboard__table">
                <table id="example" class="display textable" style="width:100%">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Hình ảnh</th>
                            <th>Vị trí đặt</th>
                            <th>TG bắt đầu</th>
                            <th>TG kết thúc</th>
                            <th>Bên quảng cáo</th>
                            <th>Sdt</th>
                            <th>Trạng thái</th>
                            <th>Hành động</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Count > 0)
                        {
                            foreach (var ad in Model)
                            {
                                stt++;
                                <tr role="row" class="odd textable" id="trad@(ad.AdvertisementId)">
                                    <td>@stt</td>
                                    <td class="tdadvert"><a href="@ad.AdLink"><img src="@ad.AdImage" /></a></td>
                                    <td>Slider @ad.AdPosition</td>
                                    <td>@ad.AdStartDate.ToString("dd-MM-yyyy")</td>
                                    <td>@ad.AdEndDate.ToString("dd-MM-yyyy")</td>
                                    <td>@ad.AdName</td>
                                    <td>@ad.AdPhone</td>
                                    <td>@ad.nameStatus</td>
                                    <td class="option text-center">
                                        <a title="Sửa" class="btn btn-primary btn-update-ad btn-del-control" href="@Url.Action("detailadvertisement","advertisement", new { id = ad.AdvertisementId })">
                                            <i class="far fa-edit"></i>
                                        </a>
                                        <a title="Xóa" class="btn danger btn-del-ad btn-del-control" input-id-ad="@ad.AdvertisementId" page-ad="list" data-toggle="modal" data-target="#exampleModalCenter">
                                            <i class="far fa-trash-alt"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>



        @*Danh sách công việc tìm kiếm nhiều nhất*@
        <div class="dashboard__content">
            <div class="dashboard__content--banner">
                <div class="row">
                    <div class="col-8">
                        <div class="dashboard__content--title">
                            <h2 class="dashboard-title">Danh sách công việc có lượt xem nhiều nhất</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="dashboard__table">
                    <table class="tablecm table--base" id="tablecm">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Tin đăng</th>
                                <th>Công việc</th>
                                <th>Ngành</th>
                                <th>Số lượt xem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (ListJobs != null && ListJobs.Count > 0)
                            {
                                foreach (var job in ListJobs.Take(10))
                                {
                                    stt++;
                                    <tr role="row">
                                        <td>@stt</td>
                                        <td>@job.RJTitle</td>
                                        <td class="tdadvert">@job.ProfessionDTO.PFName</td>
                                        <td>@job.ProfessionDTO.CareerDTO.CareerName</td>
                                        <td>@job.RJCount</td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
            </div>
        </div>

    </div>
</section>

JobHunt/Areas/Admin/Views/DashBoard/SetupWebsite.cshtml
@{
    ViewBag.Title = "SetupWebsite";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>SetupWebsite</h2>